### ISSUE TITLE
I would like to add I2P support to your Torrent Library

### ISSUE THREAD

**Issue by eyedeekay** [xgfone/go-bt#7]
I have actually already added I2P support in my fork of your library, in this tree: https://github.com/eyedeekay/bt/tree/i2p-support however it does require somewhat deep changes to how the library works. I2P is an anonymous peer-to-peer network, unlike Tor, we don't mind if people use bittorrent over I2P. Adding I2P support would allow me to use xfone/bt as an anonymous bittorrent library.

In particular this requires migrating all net.Addr's to interface types and enabling alternate implementations of all Dialers and Listeners in order to connect to I2P and accept I2P connections.

**Comment by xgfone** [comment]
`bt` only supports the network based on ip+port. close #7 #8.
